version: '3'
services:
  rasdaman:
    build: .
    volumes:
      - ./keys:/tmp/keys
    ports:
      - "127.0.0.1:50001:50001"
      - "127.0.0.1:50002:50002"
      - "127.0.0.1:50003:50003"
    working_dir: /tmp
